=pod

=encoding utf8

=head1 NAME

volumeicon - configuration file for L<volumeicon(1)>

=head1 SYNOPSIS

B<~/.config/volumeicon/volumeicon>

=head1 DESCRIPTION

L<volumeicon(1)> obtains configuration information from B<~/.config/volumeicon/volumeicon>. This configuration file can be overriden on runtime via B<--config> switch.

The configuration syntax is similar of those .ini files.

=over 4

=item B<[Alsa]>

This section holds alsa sound card configuration.

=over 4

=item B<card>

Specify which sound card to control. The default value is B<default>.

=item B<channel>

Specify the channel to control. This defaults to the first channel of the selected card/device.

=back

=item B<[StatusIcon]>

This section holds status icon configuration. The configuration items are as follows.

=over 4

=item B<stepsize>

Configure how many steps when changing volume. Takes an integer value. The default is B<5>.

=item B<onclick>

Configure the command executed when clicking B<volumeicon(1)> applet. The default is B<xterm -e 'alsamixer'>.

=back

=back

=head1 LICENSE

This program is licensed under GNU General Public License version 3. See B<COPYING> in the distribution for detailed license text.

=head1 SEE ALSO

L<volumeicon(1)>, L<alsamixer(1)>

=cut
