=pod

=encoding utf8

=head1 NAME

volumeicon - A lightweight standalone volume icon indicator (Qt port)

=head1 SYNOPSIS

B<volumeicon --config=CONFIGFILE --device=MIXER>

B<volumeicon --version>

=head1 DESCRIPTION

This app is a standalone lightweight volume icon, desktop independent, which sits on the system tray.

volumeicon accepts the following parameters.

=over 4

=item B<-c, --config=CONFIGFILE>

Alternate configuration file. Default is B<~/.config/volumeicon/volumeicon>. Refer to L<volumeicon(5)> for configuration file information.

=item B<-d, --device=MIXER>

Mixer device name

=item B<-v, --version>

Output version number and exit

=back

=head1 AUTHORS

=over 4

=item Maato <maato@softwarebakery.com>

Developer

=item Niklas Koep <niklas.koep@gmail.com>

Lots of fixes, and help on github.
 
=item Mihail Szabolcs

Notifications

=item Dan Church

Added `--with-default-mixerapp' configure option.

=item John Lindgren <john@jlindgren.net>

Qt port

=back

=head1 LICENSE

This program is licensed under GNU General Public License version 3. See B<COPYING> in the distribution for detailed license text.

=head1 SEE ALSO

L<volumeicon(5)>, L<alsamixer(1)>

=cut
